Traceback (most recent call last):
  File "/home/ubuntu/nova/villanova_research_v2/dashboard_server.py", line 136, in <module>
    main()
  File "/home/ubuntu/nova/villanova_research_v2/dashboard_server.py", line 120, in main
    server = socketserver.TCPServer((args.host, args.port), handler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
